language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - "10"
  - "8"
  - "6"
  - "11"
sudo: false
script: "npm test"
before_install:
  - "npm -g install npm"
notifications:
    slack: npm-inc:kRqQjto7YbINqHPb1X6nS3g8
